apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fwrf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0041-tenant/tkrw-pr712-0075-0041-app/devfile-sample-fwrf@sha256:5adf81ea9040599ddf74c3ce9c5579ab354b183547ff7b28392b7cc3da851f10
        name: my-nodejs
        resources: {}
status: {}
